#------------ Project Information ------------
site_name: Introducción a la Programación
site_url: 
site_description: Forward Learning Template for Python MKDocs
site_author: Adriel E. González Martínez

#------------ Project Information ends here ------------

#---------- Theme configuration ----------
theme:
  name: material
  custom_dir: material
  logo: assets/FL_Logo(Circulo)-Mkdocs-projects.png
  favicon: assets/favicon.png
  language: es #Site locale & language set to español

#----- Theme Features -----
  features:
### 1. Site header ###
  # - header.autohide

### ends ### 

### 2. Site navigation  ###
    - navigation.search
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top

### ends ###

### 3. Site Search & index  ###
    - searh.hightlight
    - search.suggest
    - searh.share

### ends ###

### 4. Table of contents (toc) ###
    - toc.follows
 #  - toc.integrate

### ends ###

### Content display ###
    - content.code.annotate
    - content.tooltips
 #  - content.tabs.links
    
### ends ###

#----- Theme Features ends here -----

#----- Theme styles -----

### Color palette ###
palette:
  - media: "(prefers-color-scheme: light)" 
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Cambiar a colores diurnos(day)
  - media: "(prefers-color-scheme: dark)" 
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Cambiar a colores nocturnos

### ends ###

### fonts ###
font:
  text: Roboto
  code: Roboto Mono

### ends ### 

### extra stylesheets ###
extra_css:
  - stylesheets/custom.css

### ends ###

#----- Theme design ends here -----

#----- MkDocs plugins -----
plugins:
  - search:
      lang: es
  - minify:
      minify_html: false
      minify_javascript: false

#----- MkDocs plugins ends here -----

#---------- Theme configuration ends here ----------

#---------- Site Footer ----------

##### Forwardlearning Copyright notice #####
copyright: Copyright &copy; 2022 <a href="http://forwardlearning.com">ForwardLearning</a> & Made with <svg id="madewithlove" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="12" height="12" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><path fill="red" fill-rule="evenodd" d="M7.655 14.916L8 14.25l.345.666a.752.752 0 0 1-.69 0zm0 0L8 14.25l.345.666l.002-.001l.006-.003l.018-.01a7.643 7.643 0 0 0 .31-.17a22.08 22.08 0 0 0 3.433-2.414C13.956 10.731 16 8.35 16 5.5C16 2.836 13.914 1 11.75 1C10.203 1 8.847 1.802 8 3.02C7.153 1.802 5.797 1 4.25 1C2.086 1 0 2.836 0 5.5c0 2.85 2.045 5.231 3.885 6.818a22.075 22.075 0 0 0 3.744 2.584l.018.01l.006.003h.002z"/></svg> by Adriel E. González Martínez
#####  ends #####

##### Forward Learning Social Media ###### 
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/forwardlearning
      name: ForwardLearning on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/forward_learning/
      name: ForwardLearning on Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/forwardlearning
      name: ForwardLearning on Youtube

##### ends ###### 

#---------- Site Footer ends here ----------

#---------- Python Markdown extensions --------
markdown_extensions:
  - md_in_html
  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true

  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#---------- Python Markdown extensions ends here --------

#---------- Site Tree & Navigation  ----------
nav:
  - Inicio: index.md
  - Python: 
    - Introducción: "python/py-intro.md"
    - Print: "python/py-print.md"
    - Input: "python/py-input.md"
    - Data Types: "python/py-datatypes.md"
    - Math: "python/py-math.md"
  - Guias:
    - ¿Tienes prisa?: "guias/guias-intro.md"
    - Python: "guias/guia-python.md"
    - Markdown: "guias/guia-markdown.md"
    - Flowcharts: "guias/guia-flowcharts.md"
  - Tutoriales: 
    - Replit: "tutoriales/tut-replit.md"
    - Arduino: "tutoriales/tut-arduino.md"
    - Sphero Bolt: "tutoriales/tut-sphero.md"

#---------- Site Tree & Navigation ends here  ----------
